name: Convert and Deploy Notebook

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Replace with your desired Python version

      - name: Install dependencies
        run: pip install nbconvert jupyter

      - name: Convert Notebook to HTML
        run: jupyter nbconvert --to html FinalProject_Group088_FA23.ipynb  # Replace with the actual filename

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout gh-pages  # Replace with the branch you're using for GitHub Pages
          mv your_notebook.html index.html  # Rename the HTML file to index.html
          git add index.html
          git commit -m "Update notebook to HTML"
          git push
